// This file is generated by scripts/sync-blog-slugs.mjs. Do not edit it by hand.
export const blogSlugs = [
  "australian-health-star-rating",
  "best-protein-powder-for-building-muscle",
  "breakup-energy",
  "calorie-calculator-how-to",
  "change",
  "healthy-low-calorie-foods",
  "healthy-organic-post",
  "idols",
  "normal",
  "reject-modernity-embrace-masculinity",
  "weak",
  "what-is-intermittent-fasting"
] as const;
